### ISSUE TITLE
Incompatible with TreeTransplant

### ISSUE THREAD

**Issue by InsaneJ** [AdvizeGH/FarmExpansion#2]
Using TreeTransplant 1.0.1, FarmExpansion 3.0.2 and SMAPI 1.15.4.
I don't get the option to "Transplant Trees" when talking to Robin. My SMAPI log shows no errors.
SMAPI log: https://paste2.org/Os9wgj1H

TreeTransplant: https://www.nexusmods.com/stardewvalley/mods/1342/?
This mod adds a menu option to Robin's farm building menu. I'm assuming this is part of the reason why these mods don't work together well. Is there anything you can do to make these mods compatible?

I've also posted this issue on TreeTransplant's Github, here: https://github.com/LeonBlade/TreeTransplant/issues/3

**Comment by AdvizeGH** [comment]
Thanks for bringing this to my attention. If my assumptions about how the TreeTransplant mod functions are correct, this incompatibility can be resolved fairly easily. I'll look at the other mod and see where the fix is best implemented.

**Comment by AdvizeGH** [comment]
Fixed in 3.1 which is now available for download.

**Comment by InsaneJ** [comment]
Thanks!
